import {IPet} from "../domain/petEntitiy";
import {v4 as uuidv4} from "uuid";

export const placeHolderPets: IPet[] = [
    {name: "Bella", age: 3, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Max", age: 5, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Charlie", age: 2, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Lucy", age: 4, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Molly", age: 1, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Buddy", age: 6, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Daisy", age: 2, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Rocky", age: 3, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Luna", age: 4, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Bailey", age: 5, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Sadie", age: 1, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Maggie", age: 6, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Jake", age: 2, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Sophie", age: 3, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Zoey", age: 4, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Coco", age: 5, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Teddy", age: 1, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Chloe", age: 6, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Roxy", age: 2, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Buster", age: 3, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Milo", age: 4, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Ruby", age: 5, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Oliver", age: 1, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Toby", age: 6, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Lily", age: 2, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Duke", age: 3, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Jack", age: 4, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Ginger", age: 5, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Riley", age: 1, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Harley", age: 6, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Oscar", age: 2, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Nala", age: 3, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Rex", age: 4, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Pepper", age: 5, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Benny", age: 1, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Jasper", age: 6, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Ellie", age: 2, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Rosie", age: 3, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Bruno", age: 4, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Layla", age: 5, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Finn", age: 1, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Moose", age: 6, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Izzy", age: 2, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Zoe", age: 3, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Tucker", age: 4, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Kiki", age: 5, species: "Cat", customerId: uuidv4(), petId: uuidv4()},
    {name: "Scout", age: 1, species: "Dog", customerId: uuidv4(), petId: uuidv4()},
    {name: "Gizmo", age: 6, species: "Cat", customerId: uuidv4(), petId: uuidv4()}
];
